parameters:
  my_pictogram.form.type.pictogram.class: Acme\Bundle\CustomBundle\Form\Type\PictogramType

services:
    pim_custom.form.type.color:
        class: Acme\Bundle\CustomBundle\Form\Type\ColorType
        tags:
            - { name: form.type, alias: acme_enrich_color }

    pim_custom.form.type.fabric:
        class: Acme\Bundle\CustomBundle\Form\Type\FabricType
        tags:
            - { name: form.type, alias: acme_enrich_fabric }

    pim_custom.form.type.brand:
        class: Acme\Bundle\CustomBundle\Form\Type\BrandType
        tags:
            - { name: form.type, alias: acme_enrich_brand }

    pim_custom.form.type.brand_mass_edit:
        class: Acme\Bundle\CustomBundle\Form\Type\BrandMassEditType
        tags:
            - { name: form.type, alias: acme_enrich_brand_mass_edit }

    pim_custom.form.type.pictogram:
        class: '%my_pictogram.form.type.pictogram.class%'
        arguments: ['@kiboko_enrich.form.event_subscriber']
        tags:
            - { name: form.type, alias: acme_enrich_pictogram }
