datagrid:
    pictogram:
        extends: pictogram-entity-grid
        options:
            entityHint: pictogram
            locale_parameter: localeCode
        source:
            #type: pim_custom_entity
            type: pim_datasource_default
            entity: Acme\Bundle\CustomBundle\Entity\Pictogram
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            labelFallback:
                label: Label
            localizedLabel:
                label: Localized Label
                data_name: translation.label
            pictureFallback:
                label: Picture
                type: twig
                template: 'KibokoEnrichBundle:Datagrid:pictureColumn.html.twig'
                data_name: pictureFallback
                frontend_type: html
            created:
                label: Created
                type: product_value_datetime
                frontend_type: datetime
            updated:
                label: Updated
                type: product_value_datetime
                frontend_type: datetime
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_customentity_edit
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_delete
                params:
                    - id
                    - customEntityName
        actions:
            show:
                type:      navigate
                label:     Show the reference data
                icon:      eye-open
                link:      show_link
            edit:
                type:      navigate
                label:     Edit the reference data
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete the reference data
                icon:  trash
                link:  delete_link
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: rd.code
                labelFallback:
                    type:      string
                    label:     Label
                    data_name: rd.labelFallback
                created:
                    type:             date
                    label:            Created
                    data_name:        rd.created
                    filter_by_having: true
                updated:
                    type:             date
                    label:            Updated
                    data_name:        rd.udapted
                    filter_by_having: true
        sorters:
            columns:
                code:
                    data_name: rd.code
                labelFallback:
                    data_name: rd.labelFallback
                created:
                    data_name: rd.created
                updated:
                    data_name: rd.udapted
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
